name: Smoke test Ruby gem
description: Tests Ruby gem installation and functionality

inputs:
  gem-file:
    description: Path to the Ruby gem file (optional, uses local if not provided)
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Smoke Ruby install
      shell: bash
      run: |
        set -euo pipefail
        tmp=$(mktemp -d)
        cp -R examples/ruby-smoke/. "$tmp"/
        pushd "$tmp" >/dev/null
        bundle config set --local path vendor/bundle

        if [[ -n "${{ inputs.gem-file }}" ]]; then
          mkdir -p vendor/local-gems
          gem unpack "${{ inputs.gem-file }}" --target vendor/local-gems >/dev/null
          gem_dir=$(find vendor/local-gems -maxdepth 1 -type d -name 'html-to-markdown-*' | head -n 1)
          bundle config set --local local.html-to-markdown "$gem_dir"
        else
          bundle config set --local local.html-to-markdown "${GITHUB_WORKSPACE}/packages/ruby"
        fi

        bundle install
        bundle exec ruby app.rb
        popd >/dev/null
        echo "✓ Ruby gem smoke test passed"
