$schema: https://github.com/Goldziher/ai-rulez/schema/ai-rules-v1.schema.json

metadata:
  name: "html-to-markdown"
  version: "1.4.0"
  description: "A modern, type-safe Python library for converting HTML to Markdown with comprehensive tag support and customizable options"

outputs:
  - file: "CLAUDE.md"
  - file: ".cursorrules"
  - file: "GEMINI.md"

rules:
  - name: "Python Code Standards"
    priority: 10
    content: |
      - Use Python 3.9+ features and type hints
      - Follow Google-style docstrings
      - Maintain 100% test coverage
      - Use ruff for linting and formatting (120 char line length)
      - Follow strict MyPy type checking
      - Use BeautifulSoup4 for HTML parsing

  - name: "Architecture Guidelines"
    priority: 9
    content: |
      - Use strategy pattern for HTML tag converters
      - Implement functional API design
      - Follow type-safe programming practices
      - Use factory pattern for converter creation
      - Maintain separation of concerns between processing and conversion

  - name: "Development Workflow"
    priority: 8
    content: |
      - Use uv for dependency management
      - Run pre-commit hooks before committing
      - Use conventional commits for commit messages
      - Test with pytest and maintain 100% coverage
      - Use GitHub Actions for CI/CD

  - name: "Code Quality"
    priority: 7
    content: |
      - No magic numbers or hardcoded values
      - Use descriptive variable and function names
      - Keep functions focused and small
      - Avoid deep nesting
      - Use early returns when appropriate
