$schema: https://github.com/Goldziher/ai-rulez/schema/ai-rules-v2.schema.json
metadata:
  description: A modern, type-safe Python library for converting HTML to Markdown with comprehensive tag support and customizable options
  name: html-to-markdown
  version: 1.4.0
outputs:
  - path: CLAUDE.md
  - path: .cursorrules
  - path: GEMINI.md
rules:
  - content: |
      - Use Python 3.9+ features and type hints
      - Follow Google-style docstrings
      - Maintain 100% test coverage
      - Use ruff for linting and formatting (120 char line length)
      - Follow strict MyPy type checking
      - Use BeautifulSoup4 for HTML parsing
    name: Python Code Standards
    priority: high
  - content: |
      - Use strategy pattern for HTML tag converters
      - Implement functional API design
      - Follow type-safe programming practices
      - Use factory pattern for converter creation
      - Maintain separation of concerns between processing and conversion
    name: Architecture Guidelines
    priority: medium
  - content: |
      - Use uv for dependency management
      - Run pre-commit hooks before committing
      - Use conventional commits for commit messages
      - Test with pytest and maintain 100% coverage
      - Use GitHub Actions for CI/CD
    name: Development Workflow
    priority: low
  - content: |
      - No magic numbers or hardcoded values
      - Use descriptive variable and function names
      - Keep functions focused and small
      - Avoid deep nesting
      - Use early returns when appropriate
    name: Code Quality
    priority: minimal
