version: "3"

# ============================================================================
# KREUZBERG THIN ROUTER - html-to-markdown
# ============================================================================
# This is the root Taskfile that delegates all work to modular task files.
# Structure:
#   - .task/config/vars.yml       -> shared variables and platform detection
#   - .task/config/platforms.yml  -> platform-specific configuration
#   - .task/languages/*           -> language-specific build/test/lint tasks
#   - .task/workflows/*           -> aggregated multi-language workflows
#   - .task/tools/*               -> utility tasks (version sync, validation, etc.)
#
# Command patterns:
#   task setup         -> installs all dependencies
#   task test          -> runs all language tests
#   task lint          -> lints all languages with auto-fix
#   task format:check  -> checks format without modifications
#   task rust:build    -> language-specific tasks (delegated to .task/languages/rust.yml)
#
# ============================================================================

# === INCLUDES ===
includes:
  # Internal configuration (not exposed as tasks)
  _cfg:
    taskfile: ./.task/config/vars.yml
    internal: true
  _platforms:
    taskfile: ./.task/config/platforms.yml
    internal: true

  # Language modules (exposed with prefix: rust:*, python:*, node:*, etc.)
  rust:
    taskfile: ./.task/languages/rust.yml
  python:
    taskfile: ./.task/languages/python.yml
  node:
    taskfile: ./.task/languages/node.yml
  typescript:
    taskfile: ./.task/languages/typescript.yml
  wasm:
    taskfile: ./.task/languages/wasm.yml
  ruby:
    taskfile: ./.task/languages/ruby.yml
  php:
    taskfile: ./.task/languages/php.yml
  go:
    taskfile: ./.task/languages/go.yml
  java:
    taskfile: ./.task/languages/java.yml
  csharp:
    taskfile: ./.task/languages/csharp.yml
  elixir:
    taskfile: ./.task/languages/elixir.yml

  # Workflow aggregators (internal, used by root-level tasks)
  _build:
    taskfile: ./.task/workflows/build.yml
    internal: true
  _test:
    taskfile: ./.task/workflows/test.yml
    internal: true
  _lint:
    taskfile: ./.task/workflows/lint.yml
    internal: true

  # Benchmark workflow (exposed as benchmark:*)
  benchmark:
    taskfile: ./.task/workflows/benchmark.yml

  # Version sync workflow
  version:
    taskfile: ./.task/tools/version-sync.yml

  # General tools (flatten to expose pre-commit:*, toml:*, shell:*, etc. at root)
  _tools:
    taskfile: ./.task/tools/general.yml
    flatten: true

# ============================================================================
# ROOT TASKS - PRIMARY DEVELOPMENT INTERFACE
# ============================================================================

tasks:
  # Setup: Install all dependencies across all languages
  setup:
    desc: "Install all dependencies and setup development environment"
    cmds:
      - task: rust:install
      - task: python:install
      - task: node:install
      - task: typescript:install
      - task: wasm:install
      - task: ruby:install
      - task: php:install
      - task: go:install
      - task: java:install
      - task: csharp:install
      - task: elixir:install
      - task: pre-commit:install

  # Build tasks: compile all languages
  build:
    desc: "Build all language bindings (default: release mode)"
    cmds:
      - task: _build:all

  build:dev:
    desc: "Build all in debug mode"
    cmds:
      - task: _build:all:dev

  build:release:
    desc: "Build all in release mode"
    cmds:
      - task: _build:all:release

  build:ci:
    desc: "Build all in CI mode"
    cmds:
      - task: _build:all:ci

  build:core:
    desc: "Build Rust core library only"
    cmds:
      - task: _build:core

  build:bindings:
    desc: "Build all language bindings (skip Rust core)"
    cmds:
      - task: _build:bindings

  build:cli:
    desc: "Build the html-to-markdown CLI binary"
    cmds:
      - task: rust:cli:build

  # Test tasks: run all test suites
  test:
    desc: "Run all test suites across all languages"
    cmds:
      - task: _test:all

  test:ci:
    desc: "Run all tests with coverage (CI mode)"
    cmds:
      - task: _test:all:ci

  # Lint tasks: linting with and without auto-fix
  lint:
    desc: "Lint all code WITH auto-fix enabled"
    cmds:
      - task: _lint:all

  lint:check:
    desc: "Lint all code WITHOUT auto-fix (check-only)"
    cmds:
      - task: _lint:check

  # Format tasks: formatting with and without modifications
  format:
    desc: "Format all code (with modifications)"
    cmds:
      - task: _lint:format

  format:check:
    desc: "Check code formatting without modifications"
    cmds:
      - task: _lint:format:check

  # Combined check: format + lint without modifications
  check:
    desc: "Run all checks (format + lint, no modifications)"
    cmds:
      - task: format:check
      - task: lint:check

  # Update dependencies: all languages
  update:
    desc: "Update all dependencies across all languages"
    cmds:
      - task: rust:update
      - task: python:update
      - task: node:update
      - task: typescript:update
      - task: wasm:update
      - task: ruby:update
      - task: php:update
      - task: go:update
      - task: java:update
      - task: csharp:update
      - task: elixir:update
      - uv tool update prek
      - prek autoupdate

  # Version synchronization: propagate version across all manifests
  versions:sync:
    desc: "Synchronize version from Cargo.toml to all package manifests"
    cmds:
      - task: version:sync

  # Coverage tasks: generate coverage reports
  cov:rust:
    desc: "Generate Rust coverage report"
    cmds:
      - task: rust:coverage

  cov:python:
    desc: "Generate Python coverage report"
    cmds:
      - task: python:coverage

  cov:all:
    desc: "Generate coverage for all languages (Rust + Python)"
    cmds:
      - task: _test:coverage

  # Benchmark tasks: performance analysis
  bench:
    desc: "Run benchmark harness (all frameworks)"
    cmds:
      - task: benchmark:harness

  bench:rust:
    desc: "Run benchmark harness for Rust only with flamegraphs"
    cmds:
      - task: benchmark:harness:rust

  bench:memory:
    desc: "Run benchmark harness with jemalloc memory stats"
    cmds:
      - task: benchmark:harness:memory

  bench:index:
    desc: "Generate flamegraph HTML index"
    cmds:
      - task: benchmark:harness:index

  bench:consolidate:
    desc: "Consolidate benchmark results under .benchmarks"
    cmds:
      - task: benchmark:harness:consolidate

  # E2E tests for published packages
  e2e:smoke:all:
    desc: "Run smoke tests for all published packages (fast validation)"
    cmds:
      - task: e2e:smoke:python
      - task: e2e:smoke:node
      - task: e2e:smoke:ruby
      - task: e2e:smoke:php
      - task: e2e:smoke:go
      - task: e2e:smoke:java
      - task: e2e:smoke:csharp
      - task: e2e:smoke:elixir

  e2e:smoke:python:
    desc: "Smoke test Python package from PyPI"
    dir: tests/test_apps/python
    cmds:
      - uv sync
      - uv run pytest smoke_test.py -v

  e2e:smoke:node:
    desc: "Smoke test Node package from npm"
    dir: tests/test_apps/node
    cmds:
      - pnpm install
      - pnpm test:smoke

  e2e:smoke:ruby:
    desc: "Smoke test Ruby gem from RubyGems"
    dir: tests/test_apps/ruby
    cmds:
      - bundle install
      - bundle exec rspec smoke_test.rb

  e2e:smoke:php:
    desc: "Smoke test PHP package from Packagist"
    dir: tests/test_apps/php
    cmds:
      - composer install
      - vendor/bin/phpunit smoke_test.php

  e2e:smoke:go:
    desc: "Smoke test Go package from pkg.go.dev"
    dir: tests/test_apps/go
    cmds:
      - go mod download
      - go test -v -run Smoke

  e2e:smoke:java:
    desc: "Smoke test Java package from Maven Central"
    dir: tests/test_apps/java
    cmds:
      - ./mvnw{{if eq .OS "windows"}}.cmd{{end}} clean install -DskipTests
      - ./mvnw{{if eq .OS "windows"}}.cmd{{end}} test -Dtest=SmokeTest

  e2e:smoke:csharp:
    desc: "Smoke test C# package from NuGet"
    dir: tests/test_apps/csharp
    cmds:
      - dotnet restore
      - dotnet test --filter FullyQualifiedName~SmokeTest

  e2e:smoke:elixir:
    desc: "Smoke test Elixir package from Hex.pm"
    dir: tests/test_apps/elixir
    cmds:
      - mix deps.get
      - mix test test/smoke_test.exs

  # Comprehensive e2e tests (post-release validation)
  e2e:test:all:
    desc: "Run comprehensive tests for all published packages"
    cmds:
      - task: e2e:test:python
      - task: e2e:test:node
      - task: e2e:test:ruby
      - task: e2e:test:php
      - task: e2e:test:go
      - task: e2e:test:java
      - task: e2e:test:csharp
      - task: e2e:test:elixir

  e2e:test:python:
    desc: "Comprehensive tests for Python package"
    dir: tests/test_apps/python
    cmds:
      - uv sync
      - uv run pytest comprehensive_test.py -v

  e2e:test:node:
    desc: "Comprehensive tests for Node package"
    dir: tests/test_apps/node
    cmds:
      - pnpm install
      - pnpm test:comprehensive

  e2e:test:ruby:
    desc: "Comprehensive tests for Ruby gem"
    dir: tests/test_apps/ruby
    cmds:
      - bundle install
      - bundle exec rspec comprehensive_test.rb

  e2e:test:php:
    desc: "Comprehensive tests for PHP package"
    dir: tests/test_apps/php
    cmds:
      - composer install
      - vendor/bin/phpunit comprehensive_test.php

  e2e:test:go:
    desc: "Comprehensive tests for Go package"
    dir: tests/test_apps/go
    cmds:
      - go mod download
      - go test -v -run Comprehensive

  e2e:test:java:
    desc: "Comprehensive tests for Java package"
    dir: tests/test_apps/java
    cmds:
      - ./mvnw{{if eq .OS "windows"}}.cmd{{end}} test -Dtest=ComprehensiveTest

  e2e:test:csharp:
    desc: "Comprehensive tests for C# package"
    dir: tests/test_apps/csharp
    cmds:
      - dotnet test --filter FullyQualifiedName~ComprehensiveTest

  e2e:test:elixir:
    desc: "Comprehensive tests for Elixir package"
    dir: tests/test_apps/elixir
    cmds:
      - mix test test/comprehensive_test.exs

  # Demo tasks
  build:demo:
    desc: "Build the GitHub Pages demo"
    cmds:
      - ./scripts/build-demo.sh

  serve:demo:
    desc: "Serve the GitHub Pages demo locally on port 8000"
    dir: docs
    cmds:
      - python3 -m http.server 8000

  # Documentation
  docs:build:
    desc: "Build documentation site with mkdocs"
    cmds:
      - task: python:install
      - uv run mkdocs build --clean --strict

  # Clean artifacts
  clean:
    desc: "Remove build artifacts across all languages"
    cmds:
      - task: rust:clean
      - task: python:clean
      - task: ruby:clean
      - task: node:clean
      - task: typescript:clean
      - task: wasm:clean
      - task: php:clean
      - task: go:clean
      - task: java:clean
      - task: csharp:clean
      - task: elixir:clean

  # Default task: show available tasks
  default:
    desc: "List available tasks"
    cmds:
      - task --list
