version: "3"

tasks:
  setup:
    desc: "Install dependencies with uv and build Rust components"
    cmds:
      - uv sync --all-extras
      - uv pip install maturin
      - maturin develop --release --manifest-path crates/html-to-markdown-py/Cargo.toml
      - prek install && prek install --hook-type commit-msg

  update:
    desc: "Update Python and Rust dependencies"
    cmds:
      - uv run uv-bump
      - cargo upgrade --incompatible
      - uv sync --all-extras --upgrade
      - maturin develop --release --manifest-path crates/html-to-markdown-py/Cargo.toml
      - prek autoupdate

  test:python:
    desc: "Run Python tests with pytest"
    cmds:
      - uv run pytest

  test:cov:
    desc: "Run Python tests with coverage"
    cmds:
      - uv run pytest --cov=html_to_markdown --cov-report=term-missing

  test:rust:
    desc: "Run Rust tests"
    cmds:
      - cargo test --release

  test:
    desc: "Run both Rust and Python tests"
    cmds:
      - task: test:rust
      - task: test:python

  lint:
    desc: "Lint Python code with ruff/prek and Rust code with clippy/fmt"
    cmds:
      - prek run --all-files

  fmt:
    desc: "Format Python and Rust code"
    cmds:
      - cargo fmt
      - prek run ruff-format --all-files

  build:
    desc: "Build Rust components for development"
    cmds:
      - maturin develop --release --manifest-path crates/html-to-markdown-py/Cargo.toml

  build:debug:
    desc: "Build Rust components in debug mode"
    cmds:
      - maturin develop --manifest-path crates/html-to-markdown-py/Cargo.toml

  build:cli:
    desc: "Build CLI binary"
    cmds:
      - cargo build --release --package html-to-markdown-cli

  clean:
    desc: "Clean build artifacts"
    cmds:
      - cargo clean
      - rm -rf target/
      - rm -rf .pytest_cache/
      - rm -rf htmlcov/
      - find . -type d -name "__pycache__" -exec rm -rf {} +
      - find . -type f -name "*.pyc" -delete

  default:
    desc: "Show available tasks"
    cmds:
      - task --list
