version: "3"

vars:
  RUST_LOG: info
  RUBY_BIN: /opt/homebrew/opt/ruby/bin
  BUNDLER_VERSION: "2.7.2"

silent: false

tasks:
  setup:
    desc: "Install all language dependencies and build the Rust core"
    cmds:
      - task: python:install
      - task: js:install
      - task: ruby:install
      - task: php:install
      - task: go:install
      - task: csharp:install
      - task: elixir:install
      - task: rust:build

  update:
    desc: "Update dependencies across Rust, JavaScript, Python, Ruby, PHP, Go, and C#"
    cmds:
      - echo "Updating Rust crates..."
      - task: rust:update
      - echo "Updating JavaScript packages..."
      - task: js:update
      - echo "Updating Ruby gems..."
      - task: ruby:update
      - echo "Updating Python dependencies..."
      - task: python:update
      - echo "Updating PHP dependencies..."
      - task: php:update
      - echo "Updating Go dependencies..."
      - task: go:update
      - echo "Updating C# dependencies..."
      - task: csharp:update
      - echo "Updating smoke test fixtures..."
      - task: examples:update

  build:
    desc: "Build Rust core and JavaScript bindings"
    cmds:
      - task: rust:build
      - task: js:build

  test:
    desc: "Run test suites for all languages"
    cmds:
      - task: rust:test
      - task: python:test
      - task: ruby:test
      - task: js:test
      - task: php:test
      - task: go:test
      - task: csharp:test
      - task: elixir:test

  lint:
    desc: "Run linters across the repo"
    cmds:
      - task: rust:lint
      - task: python:lint
      - task: ruby:lint
      - task: typescript:lint
      - task: php:lint
      - task: go:lint
      - task: csharp:lint
      - task: elixir:lint

  fmt:
    desc: "Format code for all languages"
    cmds:
      - task: rust:fmt
      - task: python:format
      - task: ruby:format
      - task: typescript:format
      - task: php:format
      - task: go:format
      - task: csharp:format
      - task: elixir:format

  bench:
    desc: "Run Rust benchmarks plus runtime harness"
    cmds:
      - task: rust:bench
      - task: bench:bindings

  bench:bindings:
    desc: "Benchmark PHP and Ruby bindings via runtime harness"
    cmds:
      - cargo run --release --manifest-path tools/runtime-bench/Cargo.toml -- --output tools/runtime-bench/results/latest.json

  bench:bindings:php:
    desc: "Benchmark PHP binding only"
    cmds:
      - cargo run --release --manifest-path tools/runtime-bench/Cargo.toml -- --language php --output tools/runtime-bench/results/php.json

  bench:bindings:ruby:
    desc: "Benchmark Ruby binding only"
    cmds:
      - cargo run --release --manifest-path tools/runtime-bench/Cargo.toml -- --language ruby --output tools/runtime-bench/results/ruby.json

  bench:bindings:profile:
    desc: "Benchmark PHP and Ruby bindings with resource profiling"
    cmds:
      - cargo run --release --manifest-path tools/runtime-bench/Cargo.toml -- --profile --output tools/runtime-bench/results/profile.json

  flamegraph:rust:
    desc: "Generate a flamegraph for the Rust core (lists_timeline fixture)"
    cmds:
      - cargo run --release --manifest-path tools/runtime-bench/Cargo.toml -- --language rust --fixture lists_timeline --flamegraph tools/runtime-bench/results/flamegraph.svg

  # Aliases (backward compatibility with legacy task names) -------------------
  test:rust:
    desc: "Alias for rust:test"
    cmds:
      - task: rust:test

  test:python:
    desc: "Alias for python:test"
    cmds:
      - task: python:test

  test:ruby:
    desc: "Alias for ruby:test"
    cmds:
      - task: ruby:test

  test:node:
    desc: "Alias for node:test"
    cmds:
      - task: node:test

  test:wasm:
    desc: "Alias for wasm:test"
    cmds:
      - task: wasm:test

  test:ts:
    desc: "Alias for typescript:test"
    cmds:
      - task: typescript:test

  test:js:
    desc: "Alias for js:test"
    cmds:
      - task: js:test

  build:cli:
    desc: "Build the html-to-markdown CLI binary"
    cmds:
      - RB_SYS_RUBY=/opt/homebrew/opt/ruby/bin/ruby RUBY=/opt/homebrew/opt/ruby/bin/ruby cargo build --release --package html-to-markdown-cli

  build:node:
    desc: "Alias for node:build"
    cmds:
      - task: node:build

  build:wasm:
    desc: "Alias for wasm:build"
    cmds:
      - task: wasm:build

  build:ts:
    desc: "Alias for typescript:build"
    cmds:
      - task: typescript:build

  build:js:
    desc: "Alias for js:build"
    cmds:
      - task: js:build

  build:demo:
    desc: "Build the GitHub Pages demo"
    cmds:
      - ./scripts/build-demo.sh

  serve:demo:
    desc: "Serve the GitHub Pages demo locally"
    dir: docs
    cmds:
      - python3 -m http.server 8000

  build:wheel-prep:
    desc: "Alias for python:wheel:prep"
    cmds:
      - task: python:wheel:prep

  cov:rust:
    desc: "Alias for rust:coverage"
    cmds:
      - task: rust:coverage

  cov:python:
    desc: "Alias for python:coverage"
    cmds:
      - task: python:coverage

  cov:all:
    desc: "Generate Rust + Python coverage reports"
    cmds:
      - task: cov:rust
      - task: cov:python

  bench:rust:
    desc: "Alias for rust:bench"
    cmds:
      - task: rust:bench

  bench:all:
    desc: "Alias for bench"
    cmds:
      - task: bench

  clean:
    desc: "Remove build artifacts across languages"
    cmds:
      - task: rust:clean
      - task: python:clean
      - task: ruby:clean
      - task: js:clean

  pre-commit:install:
    desc: "Install prek hooks (pre-commit + commit-msg)"
    cmds:
      - prek install
      - prek install --hook-type commit-msg

  pre-commit:run:
    desc: "Run all pre-commit hooks"
    cmds:
      - prek run --all-files

  # Rust tasks ----------------------------------------------------------------
  rust:build:
    desc: "Build all Rust crates"
    cmds:
      - RB_SYS_RUBY=/opt/homebrew/opt/ruby/bin/ruby RUBY=/opt/homebrew/opt/ruby/bin/ruby cargo build --workspace --exclude html-to-markdown-rb --release

  rust:test:
    desc: "Run Rust tests"
    cmds:
      - RB_SYS_RUBY=/opt/homebrew/opt/ruby/bin/ruby RUBY=/opt/homebrew/opt/ruby/bin/ruby cargo test --release --no-default-features --workspace --exclude html-to-markdown-rb

  rust:lint:
    desc: "Run Rust fmt + clippy"
    cmds:
      - cargo fmt --all
      - RB_SYS_RUBY=/opt/homebrew/opt/ruby/bin/ruby RUBY=/opt/homebrew/opt/ruby/bin/ruby cargo clippy --workspace --exclude html-to-markdown-rb -- -D warnings

  rust:fmt:
    desc: "Format Rust code"
    cmds:
      - cargo fmt --all

  rust:update:
    desc: "Update Rust dependencies"
    cmds:
      - cargo upgrade --incompatible
      - cargo update

  rust:bench:
    desc: "Run Rust benchmarks"
    cmds:
      - RB_SYS_RUBY=/opt/homebrew/opt/ruby/bin/ruby RUBY=/opt/homebrew/opt/ruby/bin/ruby cargo bench --package html-to-markdown-rs

  rust:coverage:
    desc: "Generate Rust coverage report (requires cargo-llvm-cov)"
    cmds:
      - RB_SYS_RUBY=/opt/homebrew/opt/ruby/bin/ruby RUBY=/opt/homebrew/opt/ruby/bin/ruby cargo llvm-cov --all-features --workspace --exclude html-to-markdown-py --exclude html-to-markdown-rb --lcov --output-path rust-coverage.lcov
      - RB_SYS_RUBY=/opt/homebrew/opt/ruby/bin/ruby RUBY=/opt/homebrew/opt/ruby/bin/ruby cargo llvm-cov --all-features --summary-only

  rust:clean:
    desc: "Clean Rust artifacts"
    cmds:
      - cargo clean

  # Python tasks --------------------------------------------------------------
  python:install:
    desc: "Install Python dependencies via uv"
    dir: packages/python
    cmds:
      - uv sync --all-extras

  python:update:
    desc: "Update Python dependencies"
    cmds:
      - uv run uv-bump --pyproject-toml pyproject.toml
      - uv run uv-bump --pyproject-toml packages/python/pyproject.toml
      - uv sync --all-extras --upgrade

  python:test:
    desc: "Run Python tests (build CLI first for proxy tests)"
    cmds:
      - RB_SYS_RUBY=/opt/homebrew/opt/ruby/bin/ruby RUBY=/opt/homebrew/opt/ruby/bin/ruby cargo build --release --package html-to-markdown-cli
      - uv pip install --editable packages/python
      - cmd: uv run pytest
        dir: packages/python

  python:test:cov:
    desc: "Run Python tests with coverage"
    cmds:
      - RB_SYS_RUBY=/opt/homebrew/opt/ruby/bin/ruby RUBY=/opt/homebrew/opt/ruby/bin/ruby cargo build --release --package html-to-markdown-cli
      - cmd: uv run pytest --cov=html_to_markdown --cov-report=term-missing
        dir: packages/python

  python:lint:
    desc: "Lint Python code with ruff + mypy"
    dir: packages/python
    cmds:
      - uv pip install --editable .
      - uv run ruff check
      - uv run mypy .

  python:format:
    desc: "Format Python code"
    dir: packages/python
    cmds:
      - uv run ruff check --fix
      - uv run ruff format

  python:coverage:
    desc: "Generate Python coverage lcov file"
    cmds:
      - RB_SYS_RUBY=/opt/homebrew/opt/ruby/bin/ruby RUBY=/opt/homebrew/opt/ruby/bin/ruby cargo build --release --package html-to-markdown-cli
      - cmd: uv run pytest --cov=html_to_markdown --cov-report=lcov:coverage.lcov --cov-report=term
        dir: packages/python

  python:wheel:prep:
    desc: "Prepare CLI binary for wheel packaging"
    cmds:
      - uv run scripts/prepare_wheel.py

  python:clean:
    desc: "Clean Python build artifacts"
    dir: packages/python
    cmds:
      - rm -rf build/ dist/ *.egg-info .pytest_cache .ruff_cache .mypy_cache html_to_markdown/bin

# Ruby tasks ----------------------------------------------------------------
  ruby:ensure-bundler:
    desc: "Ensure required Bundler version is installed"
    cmds:
      - PATH={{.RUBY_BIN}}:$PATH gem list -i bundler -v {{.BUNDLER_VERSION}} || PATH={{.RUBY_BIN}}:$PATH gem install bundler -v {{.BUNDLER_VERSION}} --no-document

  ruby:install:
    desc: "Install Ruby dependencies"
    cmds:
      - task: ruby:ensure-bundler
      - cmd: cd packages/ruby && PATH={{.RUBY_BIN}}:$PATH bundle _{{.BUNDLER_VERSION}}_ install

  ruby:update:
    desc: "Update Ruby dependencies"
    dir: packages/ruby
    cmds:
      - task: ruby:ensure-bundler
      - PATH={{.RUBY_BIN}}:$PATH bundle _{{.BUNDLER_VERSION}}_ update

  ruby:build:
    desc: "Build Ruby native extension"
    cmds:
      - task: ruby:ensure-bundler
      - cmd: cd packages/ruby && PATH={{.RUBY_BIN}}:$PATH bundle _{{.BUNDLER_VERSION}}_ exec rake compile

  ruby:test:
    desc: "Run Ruby specs"
    cmds:
      - task: ruby:build
      - cmd: cd packages/ruby && PATH={{.RUBY_BIN}}:$PATH bundle _{{.BUNDLER_VERSION}}_ exec rake spec

  ruby:lint:
    desc: "Lint Ruby code with Rubocop, RBS, and Steep"
    cmds:
      - task: ruby:ensure-bundler
      - cmd: cd packages/ruby && BUNDLE_PATH=vendor/bundle PATH={{.RUBY_BIN}}:$PATH bundle _{{.BUNDLER_VERSION}}_ install
      - cmd: cd packages/ruby && BUNDLE_PATH=vendor/bundle PATH={{.RUBY_BIN}}:$PATH bundle _{{.BUNDLER_VERSION}}_ exec rubocop --config ./.rubocop.yml
      - cmd: cd packages/ruby && BUNDLE_PATH=vendor/bundle PATH={{.RUBY_BIN}}:$PATH bundle _{{.BUNDLER_VERSION}}_ exec rbs validate
      - cmd: cd packages/ruby && BUNDLE_PATH=vendor/bundle PATH={{.RUBY_BIN}}:$PATH bundle _{{.BUNDLER_VERSION}}_ exec steep check

  ruby:format:
    desc: "Auto-correct Ruby lint issues"
    cmds:
      - task: ruby:ensure-bundler
      - cmd: cd packages/ruby && PATH={{.RUBY_BIN}}:$PATH bundle _{{.BUNDLER_VERSION}}_ exec rubocop --config ./.rubocop.yml --autocorrect

  ruby:clean:
    desc: "Clean Ruby build artifacts"
    dir: packages/ruby
    cmds:
      - rm -rf lib/*.bundle lib/*.so pkg/ tmp/

  # PHP tasks ----------------------------------------------------------------
  php:install:
    desc: "Install PHP dependencies"
    cmds:
      - cmd: cd packages/php && composer install --no-interaction --no-progress

  php:update:
    desc: "Update PHP dependencies"
    cmds:
      - cmd: cd packages/php && composer update --no-interaction --no-progress

  php:test:
    desc: "Run PHP test suite"
    cmds:
      - cmd: cd packages/php && composer run test

  php:lint:
    desc: "Run PHP static analysis and coding standards"
    cmds:
      - cmd: cd packages/php && composer run lint

  php:format:
    desc: "Format PHP sources"
    cmds:
      - cmd: cd packages/php && composer run format

  # Go tasks -----------------------------------------------------------------
  go:install:
    desc: "Install golangci-lint"
    cmds:
      - |
        if ! command -v golangci-lint >/dev/null 2>&1; then
          echo "Installing golangci-lint..."
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        else
          echo "golangci-lint already installed"
        fi

  go:update:
    desc: "Update Go dependencies and golangci-lint"
    cmds:
      - echo "Updating golangci-lint..."
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - echo "Updating Go module dependencies..."
      - cmd: cd packages/go && go get -u ./... && go mod tidy
      - cmd: cd examples/go-smoke && go get -u ./... && go mod tidy

  go:test:
    desc: "Run Go tests"
    cmds:
      - cargo build --release -p html-to-markdown-ffi
      - cmd: cd packages/go/htmltomarkdown && LD_LIBRARY_PATH=${GITHUB_WORKSPACE:-$PWD}/target/release:${LD_LIBRARY_PATH:-} DYLD_LIBRARY_PATH=${GITHUB_WORKSPACE:-$PWD}/target/release:${DYLD_LIBRARY_PATH:-} go test -v

  go:lint:
    desc: "Lint Go code with golangci-lint"
    cmds:
      - golangci-lint run --config .golangci.yml ./packages/go/... ./examples/go-smoke/...

  go:format:
    desc: "Format Go code"
    cmds:
      - gofmt -w packages/go examples/go-smoke

  elixir:install:
    desc: "Install Elixir dependencies and compile the NIF"
    dir: packages/elixir
    cmds:
      - MIX_ENV=dev mix deps.get
      - MIX_ENV=dev mix compile

  elixir:test:
    desc: "Run Elixir tests"
    dir: packages/elixir
    cmds:
      - MIX_ENV=test mix test

  elixir:lint:
    desc: "Lint Elixir code with Credo"
    dir: packages/elixir
    cmds:
      - MIX_ENV=dev mix credo --strict

  elixir:format:
    desc: "Format Elixir sources"
    dir: packages/elixir
    cmds:
      - MIX_ENV=dev mix format

  # C# tasks -----------------------------------------------------------------
  csharp:install:
    desc: "Verify .NET SDK is installed"
    cmds:
      - |
        if ! command -v dotnet >/dev/null 2>&1; then
          echo "ERROR: .NET SDK is not installed. Please install .NET 6.0+ SDK"
          exit 1
        fi
        echo ".NET SDK $(dotnet --version) is installed"

  csharp:update:
    desc: "Update C# NuGet dependencies"
    cmds:
      - cmd: cd packages/csharp/HtmlToMarkdown && dotnet restore --force-evaluate
      - cmd: cd packages/csharp/HtmlToMarkdown.Tests && dotnet restore --force-evaluate
      - cmd: cd examples/csharp-smoke && dotnet restore --force-evaluate

  csharp:test:
    desc: "Run C# tests"
    cmds:
      - cargo build --release -p html-to-markdown-ffi
      - cmd: cd packages/csharp/HtmlToMarkdown.Tests && LD_LIBRARY_PATH=${GITHUB_WORKSPACE:-$PWD}/../../target/release:${LD_LIBRARY_PATH:-} DYLD_LIBRARY_PATH=${GITHUB_WORKSPACE:-$PWD}/../../target/release:${DYLD_LIBRARY_PATH:-} dotnet test

  csharp:lint:
    desc: "Lint C# code (build with warnings as errors)"
    cmds:
      - cmd: cd packages/csharp/HtmlToMarkdown && dotnet build /p:TreatWarningsAsErrors=true
      - cmd: cd packages/csharp/HtmlToMarkdown.Tests && dotnet build /p:TreatWarningsAsErrors=true

  csharp:format:
    desc: "Format C# code with dotnet format"
    cmds:
      - dotnet format packages/csharp/HtmlToMarkdown/HtmlToMarkdown.csproj
      - dotnet format packages/csharp/HtmlToMarkdown.Tests/HtmlToMarkdown.Tests.csproj
      - dotnet format examples/csharp-smoke/csharp-smoke.csproj

  # Example smoke tests ------------------------------------------------------
  examples:update:
    desc: "Update all smoke test dependencies"
    cmds:
      - task: examples:node-smoke:update
      - task: examples:wasm-smoke:update
      - task: examples:ruby-smoke:update

  examples:node-smoke:update:
    desc: "Update Node smoke test dependencies"
    dir: examples/node-smoke
    cmds:
      - pnpm up --latest

  examples:wasm-smoke:update:
    desc: "Update WASM smoke test dependencies"
    dir: examples/wasm-smoke
    cmds:
      - pnpm up --latest

  examples:ruby-smoke:update:
    desc: "Update Ruby smoke test dependencies"
    cmds:
      - task: ruby:ensure-bundler
      - cmd: cd examples/ruby-smoke && PATH={{.RUBY_BIN}}:$PATH bundle _{{.BUNDLER_VERSION}}_ update

  # JavaScript / TypeScript tasks --------------------------------------------
  js:install:
    desc: "Install pnpm workspace dependencies"
    cmds:
      - pnpm install --frozen-lockfile

  js:update:
    desc: "Update pnpm workspace dependencies"
    cmds:
      - pnpm up --latest -r

  js:build:
    desc: "Build Node, WASM, and TypeScript packages"
    cmds:
      - task: node:build
      - task: wasm:build
      - task: typescript:build

  js:test:
    desc: "Run Node, WASM, and TypeScript tests"
    cmds:
      - task: node:test
      - task: wasm:test
      - task: typescript:test

  js:clean:
    desc: "Clean JS/TS build artifacts"
    cmds:
      - find crates packages -type d -name "dist" -exec rm -rf {} + 2>/dev/null || true
      - find crates packages -type d -name "node_modules" -exec rm -rf {} + 2>/dev/null || true

  node:build:
    desc: "Build Node.js native bindings"
    cmds:
      - pnpm --filter html-to-markdown-node run build

  node:test:
    desc: "Run Node.js binding tests"
    cmds:
      - pnpm --filter html-to-markdown-node test

  wasm:build:
    desc: "Build WebAssembly bindings"
    cmds:
      - pnpm --filter html-to-markdown-wasm run build:all

  wasm:test:
    desc: "Run WebAssembly tests"
    cmds:
      - pnpm --filter html-to-markdown-wasm test

  typescript:build:
    desc: "Build the TypeScript distribution"
    cmds:
      - pnpm --filter html-to-markdown run build

  typescript:test:
    desc: "Test the TypeScript distribution"
    cmds:
      - pnpm --filter html-to-markdown test

  typescript:lint:
    desc: "Lint the TypeScript distribution"
    cmds:
      - pnpm --filter html-to-markdown run lint

  typescript:format:
    desc: "Format TypeScript sources"
    cmds:
      - pnpm --filter html-to-markdown run lint:fix

  # Misc tasks ----------------------------------------------------------------
  sync-versions:
    desc: "Sync version from Cargo.toml to all package manifests"
    cmds:
      - uv run scripts/sync_versions.py

  docs:build:
    desc: "Build documentation site"
    cmds:
      - task: python:install
      - uv run mkdocs build --clean --strict

  default:
    desc: "List available tasks"
    cmds:
      - task --list
