name: Smoke test Go bindings
description: Tests Go cgo bindings with FFI library

runs:
  using: composite
  steps:
    - name: Build FFI library
      shell: bash
      run: |
        set -euo pipefail
        cargo build --release -p html-to-markdown-ffi

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.25.5"
        check-latest: true
        cache-dependency-path: examples/go-smoke/go.sum

    - name: Smoke Go install (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        set -euo pipefail
        lib_path="${GITHUB_WORKSPACE}/target/release"

        # Set CGO_LDFLAGS so the linker can find the library during build
        export CGO_LDFLAGS="-L$lib_path"

        if [[ "${{ runner.os }}" == "Linux" ]]; then
          export LD_LIBRARY_PATH="$lib_path:${LD_LIBRARY_PATH:-}"
        elif [[ "${{ runner.os }}" == "macOS" ]]; then
          export DYLD_LIBRARY_PATH="$lib_path:${DYLD_LIBRARY_PATH:-}"
        fi

        pushd examples/go-smoke >/dev/null
        go run main.go
        popd >/dev/null
        echo "✓ Go cgo bindings smoke test passed"

    - name: Smoke Go install (Windows) - SKIPPED
      if: runner.os == 'Windows'
      shell: bash
      run: |
        echo "⚠️  Go CGO smoke test skipped on Windows due to MSVC/MinGW incompatibility"
        echo "   The Rust FFI library is built with MSVC, but Go's CGO uses MinGW GCC,"
        echo "   which cannot link against MSVC libraries. This is a known limitation."
        echo "   Go bindings work correctly on Linux and macOS."
