name: Smoke test Java bindings
description: Tests Java JAR installation and functionality

inputs:
  jar-path:
    description: Path to the JAR file (optional, uses local if not provided)
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Smoke Java install
      shell: bash
      run: |
        set -euo pipefail
        tmp=$(mktemp -d)
        cp -R examples/java-smoke/. "$tmp"/
        pushd "$tmp" >/dev/null

        if [[ -n "${{ inputs.jar-path }}" ]]; then
          version="$(
            python3 - <<'PY'
        import os
        import xml.etree.ElementTree as ET
        from pathlib import Path

        pom = Path(os.environ["GITHUB_WORKSPACE"]) / "examples" / "java-smoke" / "pom.xml"
        ns = {"m": "http://maven.apache.org/POM/4.0.0"}

        tree = ET.parse(pom)
        version = None
        for dep in tree.findall(".//m:dependency", ns):
            gid = dep.find("m:groupId", ns)
            aid = dep.find("m:artifactId", ns)
            ver = dep.find("m:version", ns)
            if gid is not None and aid is not None and gid.text and aid.text:
                if gid.text.strip() == "io.github.goldziher" and aid.text.strip() == "html-to-markdown":
                    version = (ver.text if ver is not None else "").strip()
                    break

        if not version:
            raise SystemExit("Unable to determine html-to-markdown version from examples/java-smoke/pom.xml")

        print(version)
        PY
          )"

          # Install the JAR to local Maven repository
          mvn install:install-file \
            -Dfile="${{ inputs.jar-path }}" \
            -DgroupId=io.github.goldziher \
            -DartifactId=html-to-markdown \
            -Dversion="$version" \
            -Dpackaging=jar \
            -DgeneratePom=true

          # Build the native library so the smoke test can load it
          pushd "${GITHUB_WORKSPACE}" >/dev/null
          cargo build -p html-to-markdown-ffi --release
          popd >/dev/null
        else
          # Install from local packages/java/target
          pushd "${GITHUB_WORKSPACE}/packages/java" >/dev/null
          mvn install -DskipTests -Dgpg.skip=true
          popd >/dev/null
        fi

        lib_dir="$(
          python3 - <<'PY'
        import os
        from pathlib import Path

        print(Path(os.environ["GITHUB_WORKSPACE"]) / "target" / "release")
        PY
        )"

        extra_java_flags="--enable-preview --enable-native-access=ALL-UNNAMED -Djava.library.path=${lib_dir}"
        if [[ -n "${JAVA_TOOL_OPTIONS:-}" ]]; then
          export JAVA_TOOL_OPTIONS="${JAVA_TOOL_OPTIONS} ${extra_java_flags}"
        else
          export JAVA_TOOL_OPTIONS="${extra_java_flags}"
        fi

        # Compile and run the smoke test
        mvn -f pom.xml compile exec:java -Dexec.mainClass="io.github.goldziher.htmltomarkdown.SmokeTest"
        popd >/dev/null
        echo "✓ Java JAR smoke test passed"
