name: 'Build Wheels'
description: 'Build Python wheels using cibuildwheel'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'

outputs:
  artifact-name:
    description: 'Name of the uploaded artifact'
    value: wheels-${{ runner.os }}

runs:
  using: 'composite'
  steps:
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt, clippy

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install cibuildwheel
      shell: bash
      run: python -m pip install cibuildwheel==3.2.0

    - name: Build wheels
      shell: bash
      run: python -m cibuildwheel --output-dir wheelhouse packages/python
      env:
        CIBW_BUILD: cp310-* cp311-* cp312-* cp313-*

        CIBW_BEFORE_ALL_LINUX: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && source ~/.cargo/env
        CIBW_BEFORE_ALL_MACOS: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && source ~/.cargo/env
        CIBW_BEFORE_ALL_WINDOWS: >
          curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&
          refreshenv

        CIBW_BEFORE_BUILD_LINUX: >
          pip install maturin uv &&
          source ~/.cargo/env &&
          python scripts/prepare_wheel.py
        CIBW_BEFORE_BUILD_MACOS: >
          pip install maturin uv &&
          source ~/.cargo/env &&
          python scripts/prepare_wheel.py
        CIBW_BEFORE_BUILD_WINDOWS: >
          pip install maturin uv &&
          set PATH=%USERPROFILE%\.cargo\bin;%PATH% &&
          python scripts\prepare_wheel.py

        CIBW_BUILD_FRONTEND: build

        CIBW_ENVIRONMENT: MATURIN_BUILD_ARGS="--compatibility linux"
        CIBW_ENVIRONMENT_WINDOWS: MATURIN_BUILD_ARGS=""
        CIBW_ENVIRONMENT_MACOS: MATURIN_BUILD_ARGS=""

        CIBW_SKIP: "*-musllinux* *-win32 *-manylinux_i686"

        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ runner.os }}
        path: ./wheelhouse/*.whl
        retention-days: 7
