name: Build Node.js bindings
description: Builds NAPI-RS Node.js bindings and optionally creates tarball

outputs:
  tarball:
    description: Path to the packed tarball (if pack-tarball is true)
    value: ${{ steps.pack.outputs.tarball }}

inputs:
  pack-tarball:
    description: Whether to pack the result as a tarball
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Build NAPI-RS bindings
      shell: bash
      working-directory: crates/html-to-markdown-node
      run: pnpm run build

    - name: Pack Node tarball
      if: inputs.pack-tarball == 'true'
      id: pack
      shell: bash
      run: |
        set -euo pipefail
        pushd crates/html-to-markdown-node >/dev/null
        NODE_TGZ=$(npm pack | tail -1)
        mv "$NODE_TGZ" "$GITHUB_WORKSPACE/$NODE_TGZ"
        popd >/dev/null
        echo "tarball=$GITHUB_WORKSPACE/$NODE_TGZ" >> $GITHUB_OUTPUT
