name: Build PHP extension (Windows)
description: Builds PHP extension on Windows using cargo (ext-php-rs)

outputs:
  dll-path:
    description: Path to the built DLL file
    value: ${{ steps.build.outputs.dll }}

inputs:
  php-version:
    description: PHP version (e.g., "8.2")
    required: true
  php-ts:
    description: Thread safety mode (ts or nts)
    required: true

runs:
  using: composite
  steps:
    - name: Install LLVM for libclang
      shell: pwsh
      run: |
        # Install LLVM 18 via Chocolatey (LLVM 19 has incompatible MMX headers)
        choco install llvm --version=18.1.8 --allow-downgrade -y
        $llvmPath = "C:\Program Files\LLVM\bin"
        if (-not (Test-Path (Join-Path $llvmPath "libclang.dll"))) {
          throw "libclang.dll not found in LLVM installation"
        }
        Write-Host "Setting LIBCLANG_PATH=$llvmPath"
        "LIBCLANG_PATH=$llvmPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        "PATH=$llvmPath;$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Build PHP extension with cargo
      id: build
      shell: pwsh
      env:
        LIBCLANG_PATH: ${{ env.LIBCLANG_PATH }}
      run: |
        $ErrorActionPreference = "Stop"

        # Build the extension with cargo
        cargo build --package html-to-markdown-php --release

        # Find the built DLL
        $dllPath = Join-Path $env:GITHUB_WORKSPACE "target\release\html_to_markdown_php.dll"
        if (-not (Test-Path $dllPath)) {
          throw "Built DLL not found at $dllPath"
        }

        Write-Host "Built DLL at: $dllPath"
        "dll=$dllPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
