name: Docker Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKERHUB_NAMESPACE: ${{ vars.DOCKERHUB_ORGNAME || vars.DOCKERHUB_USERNAME }}

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ vars.DOCKERHUB_ORGNAME || vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO_NAME }}
          tags: |
            type=raw,value={{date 'YYYYMMDD-HHmmss'}}
            type=sha
            type=raw,value=latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
