name: Publish to Cargo

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to publish (e.g., v2.0.0)'
        required: true
        type: string

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || '' }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Extract version from tag
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            tag="${{ github.event.inputs.tag }}"
          else
            tag=${GITHUB_REF#refs/tags/}
          fi

          version=${tag#v}
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "Publishing version: $version"

      - name: Update workspace version
        run: |
          version="${{ steps.version.outputs.version }}"

          # Update workspace version in root Cargo.toml
          sed -i 's/^version = ".*"/version = "'"$version"'"/' Cargo.toml

          echo "Updated workspace version to $version"
          grep "^version" Cargo.toml

      - name: Publish core library to crates.io
        run: |
          cd crates/html-to-markdown
          cargo publish --allow-dirty --token ${{ secrets.CARGO_TOKEN }}

      - name: Wait for crates.io to index the library
        run: sleep 30

      - name: Publish CLI to crates.io
        run: |
          cd crates/html-to-markdown-cli
          cargo publish --allow-dirty --token ${{ secrets.CARGO_TOKEN }}

      - name: Verify publication
        run: |
          version="${{ steps.version.outputs.version }}"
          echo "✅ Published crates:"
          echo "  html-to-markdown: $version"
          echo "  html-to-markdown-cli: $version"
          echo ""
          echo "📦 Installation commands:"
          echo "  cargo install html-to-markdown-cli"
